### ISSUE TITLE
有些读了好多遍博客还是不太明白的问题

### ISSUE THREAD

**Issue by zuijiaoluo** [anchengjian/vue-nw-seed#1]

**Comment by anchengjian** [comment]
感谢您的意见！

然后比较抱歉的是，这个项目还没有集成 InnoSetup 等打包的东西，属于不断完善的状态中，现在只是做到了 `开发建构` 的稳定。打包相关的建构还不够稳定，现在被卡在了 `nw-builder` 这个项目，它能实现我需求的绝大部分功能，但又实现不了我期望的另外一点功能，23333，正在纠结是等他们那个项目完善还是自己重新造轮子。😂😂

另外，这个项目相对于我一个多月前的那篇开发建构而言，完善和更新了其他一些东西，用了一个侵入性更小的方式进行建构，对于这部分实践的总结，最迟这周周末我还会出一篇新文章。

最后欢迎一起讨论。

**Comment by zuijiaoluo** [comment]
好的  之前用的electron＋vue 后来用了nwjs＋vue ，webpack还是1.x的   一直都没有做安装包，正好看到你的博客，很开心能和你学习
