### ISSUE TITLE
又打扰啦~想问一下，你是怎么做到修改windows任务栏的图标的？

### ISSUE THREAD

**Issue by tangyue0924** [anchengjian/vue-nw-seed#10]
还有devtool的图标，实在是找不到你代码中是哪一块写的~~~
希望能指导一下。谢谢！~~~

**Comment by anchengjian** [comment]
蛤，不客气的，大家互相交流交流。

https://github.com/anchengjian/vue-nw-seed/blob/master/index.html#L6
和
https://github.com/anchengjian/vue-nw-seed/blob/master/package.json#L82

这两个地方，修改任务栏图标的可以直接设置 favicon 就能修改掉了。

**Comment by tangyue0924** [comment]
哈哈~谢谢拉，我这一直不显示原来是我自己的问题~~
