### ISSUE TITLE
setup.iss里的{pf}能否根据配置指定64位模式

### ISSUE THREAD

**Issue by jumkey** [anchengjian/vue-nw-seed#11]
如题
文档里说在64位模式下{pf}就是{pf64}
http://www.jrsoftware.org/ishelp/index.php?topic=32vs64bitinstalls

问题表现就是打包出来的64位安装包 默认路径是C:\Program Files (x86)

**Comment by anchengjian** [comment]
你不说我还没注意到这个细节，手动指定 `{pf64}` 是没问题的。
可以在 js 层面进行优化，在 64 位模式下，把 `{pf}` 改为 `{pf64}`

**Comment by anchengjian** [comment]
https://github.com/anchengjian/vue-nw-seed/commit/93ef234e58839c5efd1f23e67ee75afc5f6f3839

这样子或许能解决你的问题了吧

**Comment by jumkey** [comment]
嗯 就是这效果
