### ISSUE TITLE
现在更新都是下载exe文件了么，记得以前说过的增量更新没有了吗？还是后者更麻烦

### ISSUE THREAD

**Issue by iizhangchao** [anchengjian/vue-nw-seed#13]

**Comment by iizhangchao** [comment]
之前一直没有使用这个更新这个功能，现在项目上线了（是内嵌的网址，没有把网页放本地，这个体验有个不好地方就是服务器端更新了，客户端会有缓存），现在想把他成本地，然后去更新（最好增量更新）

**Comment by iizhangchao** [comment]
在安装后的文件夹里找不到html js资源，不知道打包之后放那去了

**Comment by anchengjian** [comment]
项目中的 `NW.js` 打包用的是 `nw-builder`，所以你可以在 https://github.com/anchengjian/vue-nw-seed/blob/master/config/index.js#L43-L56 这段配置中加一些相应的配置，
比如加个 [zip](https://github.com/nwjs-community/nw-builder#optionszip) 配置，解除默认的静态资源打包到 exe 中
