### ISSUE TITLE
请问下怎么把编译后的文件用作网页端

### ISSUE THREAD

**Issue by shuaizhiwen** [anchengjian/vue-nw-seed#14]
编译了之后，会有require的语法，无法在浏览器端执行

**Comment by anchengjian** [comment]
如果您的代码没有用到 `NW.js` 或者 `Node.js` 的能力，是可以直接将代码编译为浏览器用的代码的。

具体的做法：
1、[build/webpack.base.conf.js](https://github.com/anchengjian/vue-nw-seed/blob/master/build/webpack.base.conf.js#L67) 这一行代码，把这个去掉或者改为 `web`，文档在这儿[https://webpack.js.org/configuration/target/](https://webpack.js.org/configuration/target/)

2、这个项目里没加相关的取消 NW 打包配置和操作，依旧会打包 NW 的，您可以把 [build/build.js](https://github.com/anchengjian/vue-nw-seed/blob/master/build/build.js#L38)这一行注释掉，就不会打包了 NW 了。

**Comment by shuaizhiwen** [comment]
![image](https://user-images.githubusercontent.com/28283255/27846546-c98bc972-616a-11e7-931d-d1acfff535d1.png)
会报一些错误， 我会修正他，非常感谢你
