### ISSUE TITLE
npm install 不往下执行了

### ISSUE THREAD

**Issue by xianglong111** [anchengjian/vue-nw-seed#15]
您好！请问npm install 不往下执行了是怎么回事啊？
![qq 20170707171648](https://user-images.githubusercontent.com/9738743/27951599-13e50118-6338-11e7-8cc9-f57b629b165c.png)

**Comment by anchengjian** [comment]
nw的下载资源在墙外，所以，可能是下载太慢，或者。。。
你或许需要看一下我的这篇文章 [先用-npm-安装-nwjs](https://github.com/anchengjian/anchengjian.github.io/blob/master/posts/2017/vuejs-webpack-nwjs.md#1先用-npm-安装-nwjs)
