### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by xianglong111** [anchengjian/vue-nw-seed#16]
请问npm run dev之后出现这样的情况是什么问题？

![qq 20170707180517](https://user-images.githubusercontent.com/9738743/27953766-9b7875c2-633f-11e7-8b1b-a64960ef2210.png)

**Comment by anchengjian** [comment]
试试这个 [npm run dev 提示23333,bye ?](https://github.com/anchengjian/vue-nw-seed/issues/5
)
