### ISSUE TITLE
在项目使用node 模块的问题？

### ISSUE THREAD

**Issue by xianglong111** [anchengjian/vue-nw-seed#19]
您好，请问如何在该项目中使用数据库呢？例如：lowdb，测试确实无法使用。
![qq 20170714121520](https://user-images.githubusercontent.com/9738743/28198136-500530cc-688e-11e7-8ed6-2fc1f9e13657.png)

**Comment by anchengjian** [comment]
你的用法没有错，直接像 node 一样书写就可以运行的，只能给点建议了   
- 如果这个`lowdb` 需要编译的话，请用 `nw-gyp` 编译  
- 检查依赖是否是对的，建议直接把报错拿去搜一下，可能会更有效一点
