### ISSUE TITLE
fs不能使用

### ISSUE THREAD

**Issue by zuijiaoluo** [anchengjian/vue-nw-seed#2]
fs这个模块没有配置，客户端肯定是要用到的

**Comment by anchengjian** [comment]
https://nodejs.org/api/fs.html

这个是自带的系统模块，不需要配置的哦

**Comment by zuijiaoluo** [comment]
![image](https://cloud.githubusercontent.com/assets/22735208/24208604/ee7f3736-0f5e-11e7-9d8b-bf590acfe282.png)
直接直接用是可以的  移植到这个seed中  就报这个错误了
