### ISSUE TITLE
自动更新

### ISSUE THREAD

**Issue by ibullet-chzn** [anchengjian/vue-nw-seed#20]
没看懂自动更新是怎么做的，我尝试了下
实现不了啊

**Comment by anchengjian** [comment]
你需要在第二次打包的时候改下 `package.json` 的版本号。  

基本思路：
- NW.js 启动，检查更新 [src/main.js#L11](https://github.com/anchengjian/vue-nw-seed/blob/master/src/main.js#L11)
- 获取线上的 mainfest.json ，对比线上的版本和当前环境的版本，如版本不一致则跳转更新页面 [src/utils/update.js#L35-L40](https://github.com/anchengjian/vue-nw-seed/blob/master/src/utils/update.js#L35-L40)
- 更新页面就是下载文件并自动执行安装

**Comment by ibullet-chzn** [comment]
理解了，十分感谢

可以在mac下打包windows的版本嘛？

**Comment by anchengjian** [comment]
不能哦，因为 windows 在打包 setup 的时候，需要执行 innosetup.exe
