### ISSUE TITLE
安装界面的语言能选择吗？

### ISSUE THREAD

**Issue by ibullet-chzn** [anchengjian/vue-nw-seed#23]
安装界面用户协议那里，同意写的是英文，怎么可以改成中文

**Comment by anchengjian** [comment]
蛤蛤，留了注释在 [config/setup.iss](https://github.com/anchengjian/vue-nw-seed/blob/master/config/setup.iss#L61-L62) 里面，把这个注释去掉就行了

**Comment by ibullet-chzn** [comment]
好棒，点赞
