### ISSUE TITLE
build OSX64版本报错...

### ISSUE THREAD

**Issue by tangyue0924** [anchengjian/vue-nw-seed#24]
```
Successful compile (55.770 sec). Resulting Setup program filename is:
D:\hongfund\newarch\hongfund-desktop\releases\1.1.9\win32-setup\hongfund-desktop-1.1.9.exe
osx64/hongfund-desktop-1.1.9.app
(node:23464) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, stat 'D:\hongfund\newarch\hongfund-desktop\releases\1.1.9\osx64\hong
fund-desktop-1.1.9.app'
(node:23464) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
你好...
我看了下问题好像在BUILD MAC版本时,命名和写入upgrade.json的读取方式不同,请问该怎么将build时把版本号也一起加到文件名中?看了挺久代码...智商拙计...
希望能帮我这个忙~谢谢~~
@anchengjian

**Comment by tangyue0924** [comment]
我刚刚改对之后.....0.24.3 最新的NW版本的osx64的nwjs framework无访问权限

**Comment by anchengjian** [comment]
你是在 windows 上打包 OS X 的包？

**Comment by tangyue0924** [comment]
@anchengjian  是的。。Linux可以成功吗？还没有试过，如果linuxOK的话，那就OK了

**Comment by tangyue0924** [comment]
@anchengjian ...你好..打扰了...我这Linux上Build有问题,你那Linux可以吗?

**Comment by anchengjian** [comment]
是哪个版本的 Linux ？

**Comment by tangyue0924** [comment]
@anchengjian centOS 7.2 ...谢谢,错误日志提示来说,好像是因为安装包要用刀windows安装程序..这该怎么办...

**Comment by anchengjian** [comment]
o o.  

在打包 windows 安装包的时候需要 innoSetup 这个工具，而这个工具只能运行在 windows 上，😂建议不同平台打不同包，也方便测试吧，如果非要在 Linux 上打 windows 的安装包，搞个 wine 试试。顺带问一下，你的 `centOS 7.2` 的桌面是啥？

**Comment by tangyue0924** [comment]
~~~没有桌面啦...当服务器用的.....之前因为生成windows图标也想搞wine的,但是一直失败...你有啥经验吗...

**Comment by tangyue0924** [comment]
~~没有桌面啦...当服务器用的...之前也想用wine的,,但一直失败...关于wine,,你有啥经验嘛~

**Comment by tangyue0924** [comment]
没有桌面啦...当服务器用的...之前也想用wine的,,但一直失败...关于wine,,你有啥经验嘛

**Comment by anchengjian** [comment]
没有啥经验，没有试过在 Linux 上打包 windows 安装包。。。

**Comment by tangyue0924** [comment]
@anchengjian 好吧好吧~~~谢谢你了,抽空回答我这么无聊的问题,哈哈
