### ISSUE TITLE
如何单独使用inno setup安装包

### ISSUE THREAD

**Issue by Hsinky** [anchengjian/vue-nw-seed#27]
我不太喜欢用js构建工具打包，因为他们太繁琐了，可能是学的不够，希望可以得到如何单独使用安装包脚本的方法，因为我在安装了inno setup 5.5.9之后在运行提示截图的错误
![image](https://user-images.githubusercontent.com/10111222/30306692-42a220dc-97ac-11e7-9097-d592da49df9e.png)

**Comment by anchengjian** [comment]
你可能需要用 innosetup 的增强版，在 [win-beautiful-setup](https://github.com/anchengjian/vue-nw-seed/tree/win-beautiful-setup/deps/innosetup) 这个分支下我提供了一个。

JS 只是为了和 vue 项目本身的打包结合起来，然后多做了一个 innosetup 的调用而已，当然为了搞清楚背后的细节，自己折腾也是不错的。

**Comment by Hsinky** [comment]
个人拙见：可以将inno setup安装这部分独立出来，js打包这块不熟练的人真的没办法，我个人觉得挺心累的，如果有可视化工具就更好了，如果你有时间可以开发一个，因为你是大牛

**Comment by anchengjian** [comment]
当初就是觉得每次写完代码打包太麻烦了，所以才搞了这个集成的，一键打包。。。

inno setup 本身就是可视化的哦。

你可以试着用
``` bash
# default is build `setup.exe` in windows
npm run build --noSetup
```
这个命令来禁用掉命令行的 inno setup 的打包，然后用可视化工具来搞😂

**Comment by Hsinky** [comment]
非常感谢！我已经在学习你的inno setup脚本，我说的可视化工具是对vue.js,grunt.js这些打包，输入命令是很恼火的一件事情

**Comment by Hsinky** [comment]
如果能加上引导页图片轮播就更完美了，类似QQ可以鼠标点击翻滚，可以在安装的时候显示更新的功能

**Comment by anchengjian** [comment]
你琢磨下 https://github.com/anchengjian/vue-nw-seed/blob/win-beautiful-setup/config/setup.iss 这个文件。

然后弄轮播图还是很容易的，大致的思路就是把全部的可视元素给隐藏掉，然后定时器显示指定的图片。
