### ISSUE TITLE
安装依赖后运行就直接退出了

### ISSUE THREAD

**Issue by jsgr** [anchengjian/vue-nw-seed#29]
$ npm run dev

> nw-vue-play@1.0.0 dev G:\Nodejs\node-webkit\nw-vue-play
> node build/dev-server.js

> Starting dev server...
 DONE  Compiled successfully in 8204ms15:18:18

> Listening at http://localhost:8080

start with request:  http://localhost:8080/
233333,bye~~~
请问这是怎么回事。

**Comment by anchengjian** [comment]
npm run dev 提示23333,bye ? #5

**Comment by jsgr** [comment]
按这个操作了，还是退出了。而且没有开进程。我重启试了。

**Comment by anchengjian** [comment]
1、先检查 nw 的依赖是否安装完整，可以通过 node_modules/nw/nwjs/nw.exe 双击能否正常执行确认。
2、检查任务管理器，是否有当前项目下的 nwjs 相关进程未正常关闭，因为存在文件占用的问题，所以会异常退出。

不然的话，能否详细描述下重现方法，或者录个gif试试，谢谢了

**Comment by jsgr** [comment]
明天我去公司的电脑试吧。还是请问下 vue-cli 项目里面怎么调用 nw 的api 官网 都是 nw.gui

**Comment by anchengjian** [comment]
可以部分参考 [src/utils/update.js](https://github.com/anchengjian/vue-nw-seed/blob/master/src/utils/update.js) 下面的代码，直接 require 就行

**Comment by jsgr** [comment]
提示要 安装 nw.gui 模块。 
能不能 在 vue-cli 项目里 安装 nw，然后 通过 vue-cli 的打包方法 打包静态 文件出来，再用 nw 提供的打包方法打包 .exe呢？

**Comment by anchengjian** [comment]
你说的这个能不能不就是我这个种子项目么？？😂

**Comment by jsgr** [comment]
是啊，但是我目前运行不起来。其实我是用 electron-vue 做好了一个项目。然后周五可以打包。周六和周日就不能打包了。用官方提供的demo 打包都是白屏。开发环境是正常的。所以我想能不能 nw 也可以结合vue -cli 来开发。我的代码可以直接移植过来。不然要重新写。还有请问下  您 知道 electron-build 打包后白屏 是怎么回事么？

**Comment by jsgr** [comment]
还有请问下  ，我测试在 nw 项目里面 安装 第三方依赖包 。通过 require 引入。但是不生效。还有 怎么设置热更新，不用重复启动。

**Comment by jsgr** [comment]
第一次 开发这个，遇到很多问题，最开始 选择 electron 是觉得生态比较好，而且 和vue 结合了。方便开发。没想到打包是个大问题
