### ISSUE TITLE
安装之后的图标问题和安装包是英文的问题

### ISSUE THREAD

**Issue by zuijiaoluo** [anchengjian/vue-nw-seed#3]
1. 生成的安装包默认是英文的，请问下怎么改成中文的呢？
2. 生成的安装包图标是正确的，安装之后快捷方式和远exe文件的图标还是nw的，卸载程序的图标反而正常

**Comment by zuijiaoluo** [comment]
尝试了几次之后，下载了对应的依赖，图标变成正常的了（不过有一个nw的文件存在，应该是可以删除这个文件的吧），不过安装界面还是英文的

**Comment by anchengjian** [comment]
我提供了一个中文语言包。请手动打开 `./config/setup.iss` 中关于` Languages` 的注释就可以啦

**Comment by anchengjian** [comment]
图标那个应该是 windows 的缓存，你重启下电脑或者清理下文件夹图标缓存就可以看到最新的。然后
> 有一个nw的文件存在 

这个是啥玩意？  
是你污染了自己的 runtime ？

**Comment by zuijiaoluo** [comment]
有一个nw的文件存在    这个nw和我自己的启动程序是一样的  点击相同的效果  都是打开我的软件   我再研究下

**Comment by zuijiaoluo** [comment]
![image](https://cloud.githubusercontent.com/assets/22735208/24324273/73695d44-11be-11e7-9fa4-976ee2023171.png)
好像是乱码了， 我是直接在github上拉下来就是乱码的，然后到github上复制下来，还是乱码

**Comment by zuijiaoluo** [comment]
好了   用下载下来的乱码文件就可以了

**Comment by anchengjian** [comment]
因为 innosetup 的缘故，所以， iss 和 语言包都要用 ANSI 编码，utf8 等编码会乱码的。

**Comment by zuijiaoluo** [comment]
嗯，好的， 非常感谢

**Comment by zuijiaoluo** [comment]
license.txt 这个文件输入中文后，打包好也是乱码？我是要把他做成ANSI 编码还是utf8 等编码

**Comment by zuijiaoluo** [comment]
应该是ANSI 编码  你现在的还是utf8
