### ISSUE TITLE
一个担心

### ISSUE THREAD

**Issue by xland** [anchengjian/vue-nw-seed#31]
如果nw.js加载的localhost:8080
那么也就是说，我们的程序在客户端电脑上开了一个HTTP服务，
这样的话，别人只要知道他的IP地址，基本也就能访问的到他这个HTTP服务了，
如果他没做好nw.js的权限限制的话，nodejs的能力就等于暴露出来了
是不是这样呢？

**Comment by anchengjian** [comment]
不是的，这只是在开发的时候才访问本地的 8080 进行页面加载，在产品模式下打包是直接访问打包好的 index.html。
不过依然需要做 XSS 等 WEB 安全的基本防护。

**Comment by xland** [comment]
嗷~知道了~谢谢
