### ISSUE TITLE
安装目录的路径固定了vue-nw-seed

### ISSUE THREAD

**Issue by shiyuan17** [anchengjian/vue-nw-seed#35]
安装目录的路径固定了vue-nw-seed，整个项目的vue-nw-seed都修改过了，打包出来的，路径还是会显示c:\prog\vue-nw-seed

**Comment by anchengjian** [comment]
安装目录的文件夹的名字是根据项目名字传进去的，没记错的话，是 `package.json` 的 `name` 字段
