### ISSUE TITLE
增量更新

### ISSUE THREAD

**Issue by LazyNeo** [anchengjian/vue-nw-seed#37]
我想要实现增量更新的功能，请问html，js和css之类的内容打包完之后是在哪里啊？还是已经打到nw.js里面去了？

**Comment by anchengjian** [comment]
build 后的代码在 dist 目录，然后会通过 `nw-builder` 打包成一个 `vue-nw-seed.exe` ，增量的话，估计更新下发替换下  `vue-nw-seed.exe` 就行了

**Comment by LazyNeo** [comment]
这个程序包很大，下载起来也慢的




    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            neo
                            
                            
                                
                                    邮箱：535178368@qq.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制
在2018年04月08日 10:35，anchengjian 写道： build 后的代码在 dist 目录，然后会通过 nw-builder 打包成一个 vue-nw-seed.exe ，增量的话，估计更新下发替换下  vue-nw-seed.exe 就行了

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/anchengjian/vue-nw-seed","title":"anchengjian/vue-nw-seed","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/anchengjian/vue-nw-seed"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anchengjian in #37: build 后的代码在 dist 目录，然后会通过 `nw-builder` 打包成一个 `vue-nw-seed.exe` ，增量的话，估计更新下发替换下  `vue-nw-seed.exe` 就行了"}],"action":{"name":"View Issue","url":"https://github.com/anchengjian/vue-nw-seed/issues/37#issuecomment-379514510"}}}
