### ISSUE TITLE
文档会同步更新吗？还是直接博客更新

### ISSUE THREAD

**Issue by zuijiaoluo** [anchengjian/vue-nw-seed#4]
关注到忽然有更新了，但是发现博客和文档都没有更新。

**Comment by anchengjian** [comment]
有点抱歉，拖了这么久。。给这个仓库加了个项目 https://github.com/anchengjian/vue-nw-seed/projects 关于更新

这一个月又搞完一个迭代，这才空了一点点。同时这个项目又不能直接用我们项目中的单纯的 windows 下的exe安装更新，还得考虑osx / linux的更新，所以一直拖到现在。。
现在也只做了更新流程，还没测试过😂，这周周末和下周内一定会把这个搞完，搞完了应该会出一个总结，讲讲做这个过程中我是如何考虑的。

对啦，大兄弟，如果等不及你也可以发 pull requests，我给合并进去。
谢谢！

**Comment by anchengjian** [comment]
哥们，我特么还没写好。。。😂

**Comment by zuijiaoluo** [comment]
没事  我会经常关注，等你写好

**Comment by xland** [comment]
不得不给这个项目献上一个星星！

**Comment by shuaizhiwen** [comment]
这个更新搞定了吗？个人觉得linux的更新包最后出，mac其次，windows的先出即可。毕竟windows用户才是主流，而且使用nwjs的大多是为了兼容xp系统

**Comment by anchengjian** [comment]
windows 和 mac 都已经搞定了，linux 还没做😳。。。

**Comment by shuaizhiwen** [comment]
额，不好意思啊，我没仔细看，发现这个哥们问了这个问题，看了下确实没看到文档，以为没做呢

**Comment by anchengjian** [comment]
换了个新环境，有点忙不过来，这两天就把文档给补上。
对了，大兄弟，有兴趣，大家都可以提 pr 的蛤，或者把你拉为这个项目的参与者也行。

**Comment by xland** [comment]
@anchengjian ，
在杭州吗？要不要来杭州发展，研发团队，真正的RD部门，给你时间玩儿新奇的玩意儿！

**Comment by anchengjian** [comment]
@xland 蛤蛤，非常感谢给我这样的机会！不过现在我已经入职美团了，在北京😂

**Comment by shuaizhiwen** [comment]
厉害      如果有机会一定要请教一下

**Comment by anchengjian** [comment]
增加了一个 upgrade 的示例
