### ISSUE TITLE
npm run dev  提示23333,bye ? 

### ISSUE THREAD

**Issue by pengzhen-developer** [anchengjian/vue-nw-seed#5]
该问题的重现步骤是什么？
1.  下载
2.  执行 npm install
3.  执行 npm run dev

你期待的结果是什么？实际看到的又是什么？

期望看到 app 运行界面
实际看到 233333, bye~~~~~~

你正在使用产品的哪个版本？在什么操作系统上？
vue-nw-seed: 0.1.0
windows 10 * 64

如果有的话，请在下面提供更多信息。

**Comment by anchengjian** [comment]
如果依赖安装的没问题的话，我猜应该是你已经开了一个 nwjs 的相关进程没关闭掉，导致在第二次用 node 的子进程打开 nwjs 的时候报错，然后就退出了。

**Comment by iizhangchao** [comment]
同上 出现这种情况

**Comment by pengzhen-developer** [comment]
已经确定没有新开的 nwjs 的进程, 还是会出现这样的情况

**Comment by anchengjian** [comment]
1、先检查 nw 的依赖是否安装完整，可以通过 node_modules/nw/nwjs/nw.exe 双击能否正常执行确认。
2、检查任务管理器，是否有当前项目下的 nwjs 相关进程未正常关闭，因为存在文件占用的问题，所以会异常退出。

不然的话，能否详细描述下重现方法，或者录个gif试试，谢谢了

**Comment by iizhangchao** [comment]
跑起来了

**Comment by pengzhen-developer** [comment]
@anchengjian 

可能是 node 版本导致.
怀疑是 child_process.exec 导致.
更改为 child_process.execFile 试试.

**Comment by fengsduo** [comment]
我这边的问题基本与上面几位兄弟一样，请问上面的兄弟是怎么解决的？可以分享下嘛？
我用的 nw 版本：0.21.0

**Comment by bonniss** [comment]
这可能是由node.js版本引起的。
我从node.js v.12切换到v.10，问题已解决。
