### ISSUE TITLE
不能打开的开发工具，是不是被禁用

### ISSUE THREAD

**Issue by iizhangchao** [anchengjian/vue-nw-seed#6]
之前使用0.2*的时候，右键可以打开开发工具，像浏览器一样方便调试

**Comment by anchengjian** [comment]
一样的可以啊，是不是你下的不是 sdk 的 nw 包，而是 normal 的包？

**Comment by iizhangchao** [comment]
我是直接用npm 安装的， 第一次没安装上，然后直接执行 npm install nw --save 了，应该是安装了正式版了吧

**Comment by anchengjian** [comment]
你可以直接去 `node_modules/nw/nwjs/nw.exe` 执行以下，看一下版本是不是 sdk 还是 normal

**Comment by iizhangchao** [comment]
谢谢，已经确定了是安装了normal版
