### ISSUE TITLE
用这个build出来的东西，腾讯的电脑管家会报毒~

### ISSUE THREAD

**Issue by xland** [anchengjian/vue-nw-seed#9]
用这个build出来的东西，腾讯的电脑管家会报毒~

但亲测是没毒的~~~

**Comment by anchengjian** [comment]
是用 innoSetup 打包后的 exe 文件报病毒么，360报没？

**Comment by anchengjian** [comment]
只有等我晚上下班回去了再试验一下了，看看又啥解决办法

**Comment by anchengjian** [comment]
我在我虚拟机里安装了最新的 360 和腾讯电脑管家分别查杀试了下，都没报毒，也没报木马😂，是不是你那边有什么特殊的配置或者方法？

**Comment by xland** [comment]
没有，确实会报毒的，见下图，估计就是inno搞的。
![1](https://cloud.githubusercontent.com/assets/2980915/26385140/12676b5e-4070-11e7-96a2-3b744f71b0c9.jpg)

**Comment by xland** [comment]
打包好之后，安装这个安装包的时候，腾讯电脑管家会自动报毒~~~~

**Comment by anchengjian** [comment]
我下的最新的电脑管家最新的病毒库，扫描我打包出来的这个 setup.exe 和安装后的文件，都不报毒。
我怀疑会不会是你的电脑管家的病毒库不是最新的，这个原因导致被误报？
不然就只有找 NW 的版本和 innoSetup 版本的问题了，这个就不好整了，我分别去它们的 issue 里面找了下，没找到什么有用的资料。
还有就是可能真的被误报了。。。

**Comment by shuaizhiwen** [comment]
nw确实会被报毒，但是大多是误报，对于360和安全管家，只要不在他们的安全库中又有特殊权限的，都可能报毒

**Comment by anchengjian** [comment]
hi～这个问题找到原因了没，希望可以同步一下进展，让受到相同困扰的人都能得到帮助。
还有就是这个问题可以关闭了吗？😂

**Comment by xland** [comment]
暂时没找到原因~~~可以关闭吧~~~
